### ISSUE TITLE
Support environment output to_assignment?

### ISSUE THREAD

**Issue by tylerjl** [kbsecret/kbsecret#24]
Although `env` can spit out _just_ secret values and fully-formed `export` shell lines, it'd be nice to also support output of the form

```shell
VARIABLE=value
```

Which lets users prepend commands that may need environment variables with keybase commands so that something like 

```shell
$(kbsecret env aws) aws s3 ...
```

Alternatively (or in addition to) maybe there's a subcommand that could do something similar (set up an ephemeral environment variable(s) and execute the command line string). Thoughts?

**Comment by woodruffw** [comment]
> Thoughts?

I think it's a great idea.

I'll add it in a few days, unless you'd like to do a PR 😄
