### ISSUE TITLE
Make `kbsecret new-session` more consistent with other utilities

### ISSUE THREAD

**Issue by woodruffw** [kbsecret/kbsecret#25]
`kbsecret new-session` is currently invoked like this:

```bash
$ kbsecret new-session --team foo --label bar
```

Or like this, for non-team sessions:

```bash
$ kbsecret new-session --label foo --root foo --users alice,bob
```

This is inconsistent with many other `kbsecret` commands, which prefer an optionless argument for the record or session label. For example, `kbsecret rm-session`:

```bash
$ kbsecret rm-session foo
```

`new-session` should be more like `rm-session`, in order to minimize confusion and make usage more intuitive.

**Comment by lbadura** [comment]
Hey @woodruffw. I'm looking for an issue to tackle during hacktoberfest. Do you have a desired API?

**Comment by woodruffw** [comment]
Hi @lbadura,

Check out the third example in my comment above -- that's what I was thinking for the interface (CLI, not API). As for how to implement it, check out [`kbsecret rm-session`](https://github.com/kbsecret/kbsecret/blob/master/lib/kbsecret/cli/kbsecret-rm-session). It should be something pretty similar to that, where the trailing `<session>` argument is captured.

**Comment by lbadura** [comment]
Opened a PR #27
