### ISSUE TITLE
'kbsecret login nonexistent-record' should return error

### ISSUE THREAD

**Issue by dheles** [kbsecret/kbsecret#36]
* Ruby version (`ruby -v`): ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]
* KBSecret version (`kbsecret -v`): kbsecret version 0.9.4.

## Problem

Calling `kbsecret login` on a nonexistent record returns an empty string, rather than an error like similar methods do (e.g. `kbsecret pass`).

## Replication

`kbsecret login nonexistent-record`

## Expected behavior

returns `Fatal: No such record.`

## Actual behavior

returns `""`

**Comment by woodruffw** [comment]
This was originally a design decision, but I can see how it would be confusing. If you're going to make it error when a nonexistent record is requested, can you do the same for `kbsecret env`?
