### ISSUE TITLE
kbsecret new won't use --generator <my-generator> argument

### ISSUE THREAD

**Issue by dheles** [kbsecret/kbsecret#39]
* Ruby version (`ruby -v`): ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]
* KBSecret version (`kbsecret -v`): kbsecret version 0.9.4.

## Problem

I can create a new generator, but `kbsecret new` won't use it

## Replication
```
$ bundle exec kbsecret generator new test -F hex -l 64
$ bundle exec kbsecret generators -a
default
	Format: hex
	Length: 16
test
	Format: hex
	Length: 64
$ bundle exec kbsecret new login --generator test test-login
Username? test
Password?
$ bundle exec kbsecret pass test-login
notsupposedtohappen
```
Also happens with abbreviated `-g` argument.
Does not happen with default generator (`-G` argument).

## Expected behavior

Expected the password to be generated with the created generator

## Actual behavior

I needed to provide the password manually

**Comment by woodruffw** [comment]
You need to supply both `-G` and `-g` when using the non-default generator:

```
kbsecret generator new test -F hex -l 64
kbsecret new login -G -g test foo
kbsecret pass foo
```

`-G` tells `kbsecret new` to use a generator, and `-g` tells it *which* generator to use. In the absence of `-g`, `-G` falls back to the default generator. This is to distinguish between the user specifying nothing at all (i.e.wanting to fill in sensitive fields themselves) and specifying no explicit generator but expecting sensitive field generation.

**Comment by dheles** [comment]
ah. ok. an example in the docs would help. that was not evident.

**Comment by woodruffw** [comment]
Yeah, there should have been one. I added one in 8c68a90.
