### ISSUE TITLE
Modularize internal commands

### ISSUE THREAD

**Issue by woodruffw** [kbsecret/kbsecret#58]
Right now, the `kbsecret` command calls internal commands (like `list`) via `exec`, just like external commands:

```ruby
elsif external?(command) || internal?(command)
  exec expand(command), *args
```

This is slow, since it requires Ruby (and all dependent libraries) to be loaded twice: once in `kbsecret` itself, and once in the `exec`'d subcommand. It also makes it harder to generate code coverage on the CLI.

In order to avoid this reloading, all internal `kbsecret` commands should become first class objects under the `KBSecret::CLI` namespace. Some options:

* Subclass `KBSecret::CLI` in each, like `KBsecret::CLI::New` to `kbsecret new`.
* Create a new subhierarchy with a consistent mapping, like `KBSecret::CLI::Command::New` to `kbsecret new`.

**Comment by woodruffw** [comment]
Based on local testing, this results in a decent performance boost: `require "kbsecret"` takes about 400ms in total, so preventing a subcommand from needing its own brings a ~30% speedup in many cases.

**Comment by naveenanilabs** [comment]
Anyone working on this i want to help you guys.

**Comment by woodruffw** [comment]
Nope, nobody is. Feel free to take a stab!

**Comment by woodruffw** [comment]
Began work on this as #67.
