### ISSUE TITLE
Record sharing

### ISSUE THREAD

**Issue by woodruffw** [kbsecret/kbsecret#6]
A common user flow might be something like this:

1. Create a new record for testing in one's own session for testing (e.g., a new API key)
2. Once the record is finalized, add it to a group session so that others can access it

`kbsecret` currently does not provide an easy way to do this -- the user has to either manually `cp` the record file (annoying, and exposes KBSecret internal structure), or re-enter the record's fields in the new session (annoying and error prone).

It would be nice to have a `kbsecret share-record` or similar command that abstracts this task away.

Potential usage ideas:

```bash
# possible --delete or --delete-original to move the record entirely, instead of duplication
$ kbsecret share-record --from api-keys --to dev-team record1 record2 
$ kbsecret share-record api-keys dev-team record1 record2
```

**Comment by lbadura** [comment]
Since there already exist `rm` and `rm-session` perhaps for consistency's sake it would be better to name the new commands `cp-record` and `mv-record`. Also I like the version without `--from` and `--to` better - less typing and the structure of the command is familiar (cp like).

**Comment by woodruffw** [comment]
> Since there already exist rm and rm-session perhaps for consistency's sake it would be better to name the new commands cp-record and mv-record

That sounds good to me.

**Comment by lbadura** [comment]
@woodruffw Can you take a look at #50 and let me know if this is a good direction?
